import type { CSSProperties } from "react";

/** Co-located styles for CaseList (design-evals-spec: gap 11, pad 10x12, r7, ~60px, 6px between cards). */
export const s = {
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  card: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    minHeight: 60,
    boxSizing: "border-box",
    borderRadius: 7,
    background: "var(--bg-elevated)",
    border: `1px solid ${active ? "var(--border-strong)" : "var(--border)"}`,
  }),
  open: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 11,
    alignSelf: "stretch",
    cursor: "pointer",
    borderRadius: 5,
  } satisfies CSSProperties,
  icon: (color: string): CSSProperties => ({ display: "inline-flex", flexShrink: 0, color }),
  main: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0, flex: 1 } satisfies CSSProperties,
  name: { fontSize: 12.5, fontWeight: 600, color: "var(--text-primary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  subtitle: { fontSize: 11.5, color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  legacy: { color: "var(--warn)" } satisfies CSSProperties,
  tag: {
    flexShrink: 0,
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 5,
    padding: "2px 8px",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  chip: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    fontWeight: 600,
    borderRadius: 5,
    padding: "2px 8px",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  actions: (visible: boolean): CSSProperties => ({
    display: "flex",
    gap: 2,
    flexShrink: 0,
    opacity: visible ? 1 : 0.4,
    transition: "opacity .12s ease",
  }),
  actionBtn: (danger: boolean, disabled: boolean, hot: boolean): CSSProperties => ({
    width: 26,
    height: 26,
    display: "inline-grid",
    placeItems: "center",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    // Neutral at rest (design: #999 icons); delete turns red only on its own hover/focus.
    color: danger && hot && !disabled ? "var(--crit)" : "var(--text-secondary)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.4 : 1,
    padding: 0,
  }),
} as const;
