import type { CSSProperties } from "react";

const MONO = "var(--font-mono, ui-monospace, monospace)";

const chip = (color: string, bg: string): CSSProperties => ({
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  padding: "2px 8px",
  borderRadius: 5,
  border: `1px solid ${color}`,
  background: bg,
  color,
  fontFamily: MONO,
  fontSize: 12,
  overflowWrap: "anywhere",
});

export const s = {
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  item: { minWidth: 0 } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "6px 8px",
    border: "none",
    borderRadius: 6,
    background: "var(--bg-surface)",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  headIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  symbol: {
    fontFamily: MONO,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: "6px 0 0",
    padding: "0 0 0 14px",
    marginLeft: 14,
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  caller: { display: "flex", alignItems: "baseline", gap: 8, minWidth: 0 } satisfies CSSProperties,
  /** Path + symbol name. Row on desktop; the --dd-blast-caller-* vars (globals.css, max-width 767px) stack the name under the path. */
  callerBody: {
    flex: "1 1 auto",
    minWidth: 0,
    display: "flex",
    flexDirection: "var(--dd-blast-caller-dir, row)" as CSSProperties["flexDirection"],
    alignItems: "var(--dd-blast-caller-align, baseline)",
    gap: "var(--dd-blast-caller-gap, 8px)",
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  /** One line, ellipsis at the START (rtl) so the file name and :line stay visible; inner span restores LTR glyph order. */
  callerPath: {
    flex: "0 1 auto",
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    direction: "rtl",
    textAlign: "left",
  } satisfies CSSProperties,
  callerPathText: { unicodeBidi: "plaintext" } satisfies CSSProperties,
  callerName: {
    color: "var(--text-muted)",
    flex: "0 0 auto",
    maxWidth: "var(--dd-blast-caller-name-max, 60%)",
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 } satisfies CSSProperties,
  chipEndpoint: chip("var(--accent-text)", "var(--accent-bg)"),
  chipCron: chip("var(--warn)", "var(--warn-bg)"),
} as const;
