import type { CSSProperties } from "react";

const MONO = "var(--font-mono, ui-monospace, monospace)";

export const s = {
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  item: { minWidth: 0 } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "6px 8px",
    border: "none",
    borderRadius: 6,
    background: "var(--bg-surface)",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  headIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  symbol: {
    fontFamily: MONO,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: "6px 0 0",
    padding: "0 0 0 14px",
    marginLeft: 14,
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  caller: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontFamily: MONO,
    fontSize: 12,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  callerName: { color: "var(--text-muted)" } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 } satisfies CSSProperties,
  chip: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "2px 8px",
    borderRadius: 5,
    border: `1px solid ${color}`,
    background: bg,
    color,
    fontFamily: MONO,
    fontSize: 12,
    overflowWrap: "anywhere",
  }),
} as const;
