import type { CSSProperties } from "react";

/** Co-located styles for VersionsTab. Values follow the design's Versions tab. */
export const s = {
  wrap: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 4 } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 700, lineHeight: "24px" } satisfies CSSProperties,
  count: { padding: "2px 8px", gap: 5, fontSize: 11.5 } satisfies CSSProperties,
  caption: {
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    marginBottom: 16,
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  item: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  itemCurrent: { borderColor: "var(--border-strong)" } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 12, padding: "12px 14px" } satisfies CSSProperties,
  badge: {
    padding: "3px 9px",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 700,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    flexShrink: 0,
  } satisfies CSSProperties,
  badgeCurrent: { color: "var(--accent)", background: "var(--accent-bg)" } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  note: {
    display: "block",
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  noNote: {
    display: "block",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  when: { display: "block", fontSize: 11.5, lineHeight: 1.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  button: { gap: 7 } satisfies CSSProperties,
  pill: { padding: "2px 8px", gap: 5, fontSize: 11.5 } satisfies CSSProperties,
  gap: { display: "block", fontSize: 13, lineHeight: 1.5, color: "var(--text-muted)" } satisfies CSSProperties,
  gapHint: { display: "block", fontSize: 11.5, lineHeight: 1.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  skeleton: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
} as const;
